name: Downgrade
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
jobs:
  test:
    name: "Downgrade"
    strategy:
      matrix:
        group:
          - Core
        julia-version: ['1.10', '1', 'pre']
    uses: "SciML/.github/.github/workflows/downgrade.yml@v1"
    with:
      julia-version: ${{ matrix.julia-version }}
      group: ${{ matrix.group }}
      skip: "Pkg,TOML"
      allow-reresolve: false
    secrets: "inherit"
